# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9LcbxhOmbei0lSd7YAHXqWX2LzkGGON
"""

import os
import json
import math
import sqlite3
from datetime import datetime
from typing import List, Optional, Dict, Any
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()

DB_FILE = "weighsure.db"

app = FastAPI(
    title="WeighSure Metrology Verification Engine",
    description="Automated OIML R-76 verification compliance engine with persistent SQLite registry.",
    version="2.2.0",
)

# Enable CORS for frontend client communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 1. DATABASE SCHEMA & PERSISTENCE LAYER
def get_db_connection():
    """Returns a SQLite connection with dict-like row mapping."""
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    """Initializes the SQLite schema and seeds standard reference reports if empty."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS reports (
        id TEXT PRIMARY KEY,
        created_at TEXT NOT NULL,
        serial_number TEXT NOT NULL,
        manufacturer TEXT NOT NULL,
        model TEXT NOT NULL,
        accuracy_class TEXT NOT NULL,
        max_capacity REAL NOT NULL,
        scale_interval_e REAL NOT NULL,
        overall_verdict TEXT NOT NULL,
        verification_hash TEXT NOT NULL,
        full_json TEXT NOT NULL
    )
    """)
    conn.commit()
    cursor.execute("SELECT COUNT(*) as count FROM reports")
    row_count = cursor.fetchone()["count"]
    if row_count == 0:
      for benchmark in BENCHMARK_REPORTS:
          evaluated = evaluate_oiml_report(benchmark)
          persist_report(evaluated, conn)
    conn.close()

def persist_report(report_data: dict, conn=None):
    """Inserts or updates an OIML report inside SQLite."""
    local_conn = conn or get_db_connection()
    cursor = local_conn.cursor()
    inst = report_data.get("instrument", {})

    cursor.execute("""
    INSERT OR REPLACE INTO reports (
        id, created_at, serial_number, manufacturer, model,
        accuracy_class, max_capacity, scale_interval_e,
        overall_verdict, verification_hash, full_json
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        report_data.get("id"),
        report_data.get("createdAt", datetime.utcnow().isoformat() + "Z"),
        inst.get("serialNumber", "UNKNOWN"),
        inst.get("manufacturer", "Generic"),
        inst.get("model", "Standard"),
        inst.get("accuracyClass", "CLASS_III"),
        float(inst.get("maxCapacity", 30.0)),
        float(inst.get("scaleIntervalE", 0.005)),
        report_data.get("overallVerdict", "PENDING"),
        report_data.get("verificationHash", ""),
        json.dumps(report_data)
    ))

    if not conn:
        local_conn.commit()
        local_conn.close()

def calculate_mpe(load_val: float, accuracy_class: str, e: float, is_in_service: bool = False) -> float:
    """
    Computes Maximum Permissible Error (MPE) as prescribed by OIML R-76 Table 6.
    Class I, II, III, and IV limits based on verification scale intervals (m = m/e).
    """
    if e <= 0:
        return 0.0

    m = abs(load_val) / e
    factor = 0.5
    acc = str(accuracy_class).upper()

    if "I" in acc and "II" not in acc and "IV" not in acc:  # Special Accuracy Class I
        if m <= 50000:
            factor = 0.5
        elif m <= 200000:
            factor = 1.0
        else:
            factor = 1.5
    elif "II" in acc and "III" not in acc:  # High Accuracy Class II
        if m <= 5000:
            factor = 0.5
        elif m <= 20000:
            factor = 1.0
        else:
            factor = 1.5
    elif "IV" in acc:  # Ordinary Accuracy Class IV
        if m <= 50:
            factor = 0.5
        elif m <= 200:
            factor = 1.0
        else:
            factor = 1.5
    else:  # Medium Accuracy Class III (Commercial & Industrial Standard)
        if m <= 500:
            factor = 0.5
        elif m <= 2000:
            factor = 1.0
        else:
            factor = 1.5

    # In-service verification tolerance is double the initial verification tolerance
    multiplier = 2.0 if is_in_service else 1.0
    return round(factor * e * multiplier, 6)

def evaluate_oiml_report(report: dict) -> dict:
    """
    Deterministic evaluation of:
    1. Weighing Performance & Hysteresis
    2. Eccentricity (Corner Load)
    3. Repeatability (Reproducibility & Variance)
    """
    specs = report.get("instrument", {})
    e = float(specs.get("scaleIntervalE", 0.005))
    acc_class = specs.get("accuracyClass", "CLASS_III")
    is_in_service = report.get("verificationType") == "in_service"

    # 1. Weighing Test
    weighing_points = report.get("weighingTest", [])
    weighing_passed = True
    for p in weighing_points:
        load = float(p.get("nominalLoad", 0.0))
        mpe = calculate_mpe(load, acc_class, e, is_in_service)
        p["mpe"] = mpe

        inc = float(p.get("indicatedIncreasing", load))
        dec = float(p.get("indicatedDecreasing", load))
        err_inc = round(inc - load, 6)
        err_dec = round(dec - load, 6)

        p["errorIncreasing"] = err_inc
        p["errorDecreasing"] = err_dec
        p["hysteresis"] = round(abs(inc - dec), 6)
        p["passIncreasing"] = abs(err_inc) <= (mpe + 1e-9)
        p["passDecreasing"] = abs(err_dec) <= (mpe + 1e-9)
        p["passOverall"] = p["passIncreasing"] and p["passDecreasing"]

        if not p["passOverall"]:
            weighing_passed = False

    # 2. Eccentricity Test (Corner Loading)
    ecc_points = report.get("eccentricityTest", [])
    ecc_passed = True
    readings = []
    for c in ecc_points:
        load = float(c.get("appliedLoad", float(specs.get("maxCapacity", 30)) / 3))
        mpe = calculate_mpe(load, acc_class, e, is_in_service)
        c["mpe"] = mpe
        ind = float(c.get("indicatedValue", load))
        readings.append(ind)
        err = round(ind - load, 6)
        c["error"] = err
        c["pass"] = abs(err) <= (mpe + 1e-9)

        if not c["pass"]:
            ecc_passed = False

    max_diff = round(max(readings) - min(readings), 6) if readings else 0.0

    # 3. Repeatability Test
    rep = report.get("repeatabilityTest", {})
    runs = rep.get("runs", [])
    rep_passed = True
    rep_values = [float(r.get("indicatedValue", 0.0)) for r in runs if "indicatedValue" in r]

    if rep_values:
        rep_load = float(rep.get("appliedLoad", float(specs.get("maxCapacity", 30)) * 0.5))
        mpe_rep = calculate_mpe(rep_load, acc_class, e, is_in_service)
        rep["mpe"] = mpe_rep
        range_diff = round(max(rep_values) - min(rep_values), 6)
        rep["rangeDifference"] = range_diff
        rep["maxReading"] = max(rep_values)
        rep["minReading"] = min(rep_values)
        mean_val = sum(rep_values) / len(rep_values)
        variance = sum((x - mean_val) ** 2 for x in rep_values) / len(rep_values)
        rep["stdDev"] = round(math.sqrt(variance), 6)
        rep_passed = range_diff <= (mpe_rep + 1e-9)
        rep["pass"] = rep_passed

    overall_verdict = "PASS" if (weighing_passed and ecc_passed and rep_passed) else "FAIL"
    clean_id = "".join(filter(str.isalnum, str(report.get("id", "REPORT"))))
    v_hash = (
        f"SHA256-OIML76-CERTIFIED-{clean_id}"
        if overall_verdict == "PASS"
        else f"SHA256-FAIL-NONCONFORMING-{clean_id}"
    )

    report.update({
        "weighingTestPassed": weighing_passed,
        "eccentricityTestPassed": ecc_passed,
        "eccentricityMaxDiff": max_diff,
        "repeatabilityTestPassed": rep_passed,
        "overallVerdict": overall_verdict,
        "verificationHash": v_hash,
    })
    return report

# 3. BENCHMARK SEED DATA

BENCHMARK_REPORTS = [
    {
        "id": "RRSL-2026-0042",
        "createdAt": "2026-09-09T10:30:00Z",
        "verificationType": "initial",
        "instrument": {
            "manufacturer": "Essae-Teraoka Ltd.",
            "model": "DS-252 HD Precision",
            "serialNumber": "ES-2026-98114",
            "accuracyClass": "CLASS_III",
            "maxCapacity": 30.0,
            "minCapacity": 0.1,
            "scaleIntervalE": 0.005,
            "unit": "kg",
        },
        "environment": {
            "temperature": 22.4,
            "humidity": 52.0,
            "labName": "Regional Reference Standards Laboratory (RRSL)",
            "labLocation": "Faridabad, Haryana",
            "officerName": "Aaditya Sachan (LMO-408)",
            "officerId": "IND-LM-2026-408",
            "testingDate": "2026-09-09",
        },
        "weighingTest": [
            {"id": "wp-min", "nominalLoad": 0.1, "indicatedIncreasing": 0.1, "indicatedDecreasing": 0.1},
            {"id": "wp-2.5", "nominalLoad": 2.5, "indicatedIncreasing": 2.502, "indicatedDecreasing": 2.501},
            {"id": "wp-10", "nominalLoad": 10.0, "indicatedIncreasing": 10.003, "indicatedDecreasing": 10.004},
            {"id": "wp-20", "nominalLoad": 20.0, "indicatedIncreasing": 20.005, "indicatedDecreasing": 20.006},
            {"id": "wp-30", "nominalLoad": 30.0, "indicatedIncreasing": 30.006, "indicatedDecreasing": 30.006},
        ],
        "eccentricityTest": [
            {"position": "Center (1)", "appliedLoad": 10.0, "indicatedValue": 10.002},
            {"position": "Front-Left (2)", "appliedLoad": 10.0, "indicatedValue": 10.003},
            {"position": "Back-Left (3)", "appliedLoad": 10.0, "indicatedValue": 10.001},
            {"position": "Back-Right (4)", "appliedLoad": 10.0, "indicatedValue": 10.004},
            {"position": "Front-Right (5)", "appliedLoad": 10.0, "indicatedValue": 10.002},
        ],
        "repeatabilityTest": {
            "appliedLoad": 15.0,
            "runs": [
                {"runNumber": 1, "indicatedValue": 15.002},
                {"runNumber": 2, "indicatedValue": 15.003},
                {"runNumber": 3, "indicatedValue": 15.001},
                {"runNumber": 4, "indicatedValue": 15.002},
                {"runNumber": 5, "indicatedValue": 15.003},
            ],
        },
        "overallVerdict": "PASS",
        "notes": "Verified fully compliant with OIML R-76 statutory provisions.",
    },
    {
        "id": "RRSL-2026-0043",
        "createdAt": "2026-09-08T14:15:00Z",
        "verificationType": "initial",
        "instrument": {
            "manufacturer": "Apex Tech Weighers",
            "model": "ATW-150-M",
            "serialNumber": "APX-77402",
            "accuracyClass": "CLASS_III",
            "maxCapacity": 15.0,
            "minCapacity": 0.04,
            "scaleIntervalE": 0.002,
            "unit": "kg",
        },
        "environment": {
            "temperature": 25.1,
            "humidity": 61.0,
            "labName": "Legal Metrology Standards Lab",
            "labLocation": "Jaipur, Rajasthan",
            "officerName": "Aaditya Sachan (LMO-408)",
            "officerId": "IND-LM-2026-408",
            "testingDate": "2026-09-08",
        },
        "weighingTest": [
            {"id": "wp-1", "nominalLoad": 0.04, "indicatedIncreasing": 0.04, "indicatedDecreasing": 0.04},
            {"id": "wp-2", "nominalLoad": 5.0, "indicatedIncreasing": 5.001, "indicatedDecreasing": 5.001},
            {"id": "wp-3", "nominalLoad": 15.0, "indicatedIncreasing": 15.004, "indicatedDecreasing": 15.004},
        ],
        "eccentricityTest": [
            {"position": "Center (1)", "appliedLoad": 5.0, "indicatedValue": 5.001},
            {"position": "Front-Left (2)", "appliedLoad": 5.0, "indicatedValue": 5.002},
            {"position": "Back-Left (3)", "appliedLoad": 5.0, "indicatedValue": 5.001},
            {"position": "Back-Right (4)", "appliedLoad": 5.0, "indicatedValue": 5.006},  # Exceeds MPE
            {"position": "Front-Right (5)", "appliedLoad": 5.0, "indicatedValue": 5.002},
        ],
        "repeatabilityTest": {
            "appliedLoad": 7.5,
            "runs": [
                {"runNumber": 1, "indicatedValue": 7.501},
                {"runNumber": 2, "indicatedValue": 7.502},
                {"runNumber": 3, "indicatedValue": 7.501},
            ],
        },
        "overallVerdict": "FAIL",
        "notes": "Rejected: Back-Right corner exceeds allowable maximum permissible error.",
    },
]

# Initialize Database Schema
init_db()

# 4. REST API ENDPOINTS
@app.get("/api/health")
def health_status():
    """Returns runtime health, database driver status, and persistent record count."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) as count FROM reports")
    total = cursor.fetchone()["count"]
    conn.close()

    return {
        "status": "healthy",
        "database": "SQLite (weighsure.db)",
        "persistenceMode": "Local Persistent Disk Storage",
        "totalRecords": total,
        "engine": "OIML R-76 Deterministic NAWI Compliance Engine",
        "timestamp": datetime.utcnow().isoformat() + "Z",
    }

@app.get("/api/reports")
def list_reports():
    """Retrieves all verification records from the SQLite database."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT full_json FROM reports ORDER BY created_at DESC")
    rows = cursor.fetchall()
    conn.close()
    return [json.loads(r["full_json"]) for r in rows]

@app.get("/api/reports/{report_id}")
def get_report(report_id: str):
    """Retrieves a specific test report by unique identifier."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT full_json FROM reports WHERE id = ?", (report_id,))
    row = cursor.fetchone()
    conn.close()

    if not row:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Report '{report_id}' was not found in the SQLite register.",
        )
    return json.loads(row["full_json"])

@app.post("/api/reports")
def create_or_update_report(report: dict):
    """
    Evaluates raw test measurements against OIML R-76 MPE limits
    and immediately persists the computed results into SQLite.
    """
    rep_id = report.get("id")
    if not rep_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Attribute 'id' is required for verification reports.",
        )

    evaluated = evaluate_oiml_report(report)
    persist_report(evaluated)
    return evaluated

@app.post("/api/reports/reset")
def reset_to_benchmark_seeds():
    """Resets the SQLite repository back to initial benchmark records."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM reports")
    conn.commit()

    for benchmark in BENCHMARK_REPORTS:
        evaluated = evaluate_oiml_report(benchmark)
        persist_report(evaluated, conn)

    cursor.execute("SELECT full_json FROM reports ORDER BY created_at DESC")
    rows = cursor.fetchall()
    conn.close()
    return [json.loads(r["full_json"]) for r in rows]

@app.get("/api/verify/{report_id}")
def verify_certificate_qr(report_id: str):
    """
    Public registry verification endpoint executed when inspecting
    the QR code stamped on the physical Legal Metrology Certificate.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT full_json FROM reports WHERE id = ?", (report_id,))
    row = cursor.fetchone()
    conn.close()

    if not row:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Verification certificate not found in Legal Metrology National Registry.",
        )

    report = json.loads(row["full_json"])
    inst = report.get("instrument", {})
    env = report.get("environment", {})

    return {
        "verified": True,
        "dataSource": "Official SQLite Metrological Ledger",
        "reportId": report.get("id"),
        "manufacturer": inst.get("manufacturer"),
        "model": inst.get("model"),
        "serialNumber": inst.get("serialNumber"),
        "accuracyClass": inst.get("accuracyClass"),
        "maxCapacity": f"{inst.get('maxCapacity')} {inst.get('unit', 'kg')}",
        "scaleIntervalE": f"{inst.get('scaleIntervalE')} {inst.get('unit', 'kg')}",
        "testingDate": env.get("testingDate"),
        "testingOfficer": env.get("officerName"),
        "officerId": env.get("officerId"),
        "laboratory": f"{env.get('labName')}, {env.get('labLocation')}",
        "overallVerdict": report.get("overallVerdict"),
        "verificationHash": report.get("verificationHash"),
        "weighingTestPassed": report.get("weighingTestPassed"),
        "eccentricityTestPassed": report.get("eccentricityTestPassed"),
        "repeatabilityTestPassed": report.get("repeatabilityTestPassed"),
    }

class ExplainRequest(BaseModel):
    question: Optional[str] = "Provide metrological diagnosis"
    reportData: dict
    language: Optional[str] = "en"

@app.post("/api/gemini/explain")
def explain_diagnosis(req: ExplainRequest):
    """Metrology diagnostic assistant providing technical analysis in clear English."""
    report = req.reportData
    is_pass = report.get("overallVerdict") == "PASS"
    inst = report.get("instrument", {})
    unit = inst.get("unit", "kg")

    failed_corners = [c for c in report.get("eccentricityTest", []) if not c.get("pass", True)]
    failed_weighing = [w for w in report.get("weighingTest", []) if not w.get("passOverall", True)]
    rep_failed = not report.get("repeatabilityTestPassed", True)

    if is_pass:
        text = (
            f"**OIML R-76 Technical Verification: CONFORMING (PASS)**\n\n"
            f"The non-automatic weighing instrument **{inst.get('manufacturer')} {inst.get('model')}** "
            f"(Accuracy Class: {inst.get('accuracyClass')}, Max: {inst.get('maxCapacity')} {unit}, e: {inst.get('scaleIntervalE')} {unit}) "
            f"conforms to statutory verification limits under OIML Recommendation R-76.\n\n"
            f"• **Weighing Accuracy**: All measured loading and unloading points are strictly within MPE tolerances.\n"
            f"• **Eccentricity (Corner Load)**: Platter loading points show acceptable deviation across quadrants.\n"
            f"• **Repeatability**: Repeated test cycles demonstrate standard deviation below statutory limit.\n\n"
            f"**Conclusion**: The instrument satisfies statutory criteria. Physical stamping and certification are approved."
        )
    else:
        text = (
            f"**OIML R-76 Non-Conformance Diagnosis: REJECTED (FAIL)**\n\n"
            f"The instrument **{inst.get('manufacturer')} {inst.get('model')}** failed statutory tolerances:\n\n"
        )
        if failed_corners:
            corner_names = ", ".join([c.get("position", "") for c in failed_corners])
            text += f"• **Corner Eccentricity Failure**: Significant shift detected at {corner_names} exceeding MPE.\n"
        if failed_weighing:
            text += "• **Weighing Accuracy Failure**: High-capacity loading errors exceeded the permissible envelope.\n"
        if rep_failed:
            text += "• **Repeatability Failure**: Variance across identical test cycles exceeded allowable limits.\n"
        text += (
            "\n**Corrective Engineering Steps**:\n"
            "1. Inspect platter seating and clear debris from mechanical overload stops.\n"
            "2. Verify base leveling using the spirit level bubble.\n"
            "3. Trim the load cell summing junction potentiometers for corner balance.\n"
            "4. Perform span calibration using calibrated Class F or M1 reference standards."
        )

    return {
        "text": text,
        "source": "deterministic_python_sqlite_engine",
    }

dist_dir = os.path.join(os.getcwd(), "dist") # Changed __file__ to os.getcwd()
if os.path.exists(dist_dir):
    app.mount("/assets", StaticFiles(directory=os.path.join(dist_dir, "assets")), name="assets")

    @app.get("/{full_path:path}")
    def serve_frontend(full_path: str):
        file_path = os.path.join(dist_dir, full_path)
        if os.path.exists(file_path) and os.path.isfile(file_path):
            return FileResponse(file_path)
        return FileResponse(os.path.join(dist_dir, "index.html"))

if __name__ == "__main__":
    import uvicorn
    print("\n" + "=" * 60)
    print("⚖️  WeighSure Metrology Verification System (FastAPI + SQLite)")
    print("💾 Local SQLite Ledger: weighsure.db")
    print("🚀 Full App (UI + Backend): http://localhost:8000")
    print("📖 Interactive API Docs: http://localhost:8000/docs")
    print("=" * 60 + "\n")
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)